### ISSUE TITLE
reload! doesn't appear to reload Arel in Rails Console

### ISSUE THREAD

**Issue by eddorre** [nkallen/arel#1]
When calling reload! to reload rails console session, Arel seems to unload.

Using ruby-1.9.2-p-1 with rvm and Rails 3b3.

Steps to reproduce:

rails c
Call scope on a model (Post.spam)
reload!
Call scope on model again (Post.spam)

NameError: uninitialized constant Arel
    from /Users/carlos/.rvm/gems/ruby-1.9.2-head/gems/activerecord-3.0.0.beta3/lib/active_record/base.rb:1032:in `arel_table'
    from /Users/carlos/.rvm/gems/ruby-1.9.2-head/gems/activerecord-3.0.0.beta3/lib/active_record/base.rb:1027:in`unscoped'
    from /Users/carlos/.rvm/gems/ruby-1.9.2-head/gems/activerecord-3.0.0.beta3/lib/active_record/named_scope.rb:30:in `scoped'
    from /Users/carlos/.rvm/gems/ruby-1.9.2-head/gems/activerecord-3.0.0.beta3/lib/active_record/base.rb:405:in`where'
    from /Users/carlos/work/jquery_slider_rails3/app/models/stock.rb:2:in `block in <class:Stock>'
    from /Users/carlos/.rvm/gems/ruby-1.9.2-head/gems/activerecord-3.0.0.beta3/lib/active_record/named_scope.rb:95:in`call'
    from /Users/carlos/.rvm/gems/ruby-1.9.2-head/gems/activerecord-3.0.0.beta3/lib/active_record/named_scope.rb:95:in `block in scope'
    from /Users/carlos/.rvm/gems/ruby-1.9.2-head/gems/activerecord-3.0.0.beta3/lib/active_record/named_scope.rb:104:in`call'
    from /Users/carlos/.rvm/gems/ruby-1.9.2-head/gems/activerecord-3.0.0.beta3/lib/active_record/named_scope.rb:104:in `block (2 levels) in scope'
    from (irb):5
    from /Users/carlos/.rvm/gems/ruby-1.9.2-head/gems/railties-3.0.0.beta3/lib/rails/commands/console.rb:47:in`start'
    from /Users/carlos/.rvm/gems/ruby-1.9.2-head/gems/railties-3.0.0.beta3/lib/rails/commands/console.rb:8:in `start'
    from /Users/carlos/.rvm/gems/ruby-1.9.2-head/gems/railties-3.0.0.beta3/lib/rails/commands.rb:34:in`<top (required)>'
    from script/rails:9:in `require'
    from script/rails:9:in`<main>'

**Comment by ghost** [comment]
Can't reproduce this on Rails master and 1.9.2-head. Can you upgrade to Rails 3 beta 4 and try again?

**Comment by eddorre** [comment]
Looks like upgrading to Beta 4 did the trick. Thanks!
